import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

class AppTheme {
  static final ThemeData themeData = FlexThemeData.light(
    scheme: FlexScheme.hippieBlue,
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffoldVariantDialog,
    blendLevel: 10,
    appBarElevation: 2.0,
    tabBarStyle: FlexTabBarStyle.forBackground,
    subThemesData: const FlexSubThemesData(
      thinBorderWidth: 0.5,
      thickBorderWidth: 0.5,
    
      defaultRadius: 25.0,
      textButtonRadius: 25.0,
      elevatedButtonRadius: 25.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimary,
      elevatedButtonSecondarySchemeColor: SchemeColor.onPrimaryContainer,
      outlinedButtonRadius: 25.0,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 0.5,
      toggleButtonsRadius: 40.0,
      sliderTrackHeight: 1,
      inputDecoratorIsFilled: false,
      inputDecoratorRadius: 25.0,
      inputDecoratorFocusedBorderWidth: 0.5,
      fabUseShape: true,
      fabAlwaysCircular: true,
      chipSchemeColor: SchemeColor.background,
      chipSelectedSchemeColor: SchemeColor.primaryContainer,
      chipDeleteIconSchemeColor: SchemeColor.onPrimaryContainer,
      chipRadius: 25.0,
      cardRadius: 25.0,
      popupMenuRadius: 12.0,
      popupMenuElevation: 2.0,
      popupMenuSchemeColor: SchemeColor.onPrimary,
      tooltipSchemeColor: SchemeColor.onPrimaryContainer,
      dialogBackgroundSchemeColor: SchemeColor.onPrimary,
      dialogRadius: 25.0,
      timePickerDialogRadius: 25.0,
      appBarBackgroundSchemeColor: SchemeColor.background,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.secondary,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.secondary,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.secondary,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.secondary,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarShowUnselectedLabels: false,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.primary,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailUnselectedIconSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 0.23,
      navigationRailLabelType: NavigationRailLabelType.selected,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
  );

  static final ThemeData darkTheme = FlexThemeData.dark(
    scheme: FlexScheme.hippieBlue,
    surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
    blendLevel: 19,
    tabBarStyle: FlexTabBarStyle.forBackground,
    subThemesData: const FlexSubThemesData(
      defaultRadius: 20.0,
      thinBorderWidth: 0.5,
      menuBarRadius: 25.0,
      thickBorderWidth: 0.5,
      textButtonRadius: 20.0,
      elevatedButtonRadius: 20.0,
      elevatedButtonSchemeColor: SchemeColor.onPrimary,
      elevatedButtonSecondarySchemeColor: SchemeColor.onPrimaryContainer,
      outlinedButtonRadius: 20.0,
      outlinedButtonBorderWidth: 0.5,
      outlinedButtonPressedBorderWidth: 0.5,
      toggleButtonsRadius: 40.0,
      sliderTrackHeight: 1,
      inputDecoratorIsFilled: false,
      inputDecoratorRadius: 20.0,
      inputDecoratorFocusedBorderWidth: 0.5,
      fabUseShape: true,
      defaultRadiusAdaptive: 25.0,
      menuRadius: 25.0,
      fabAlwaysCircular: true,
      chipSchemeColor: SchemeColor.background,
      chipSelectedSchemeColor: SchemeColor.primaryContainer,
      chipDeleteIconSchemeColor: SchemeColor.onPrimaryContainer,
      chipRadius: 20.0,
      cardRadius: 20.0,
      popupMenuRadius: 12.0,
      popupMenuElevation: 2.0,
      popupMenuSchemeColor: SchemeColor.onPrimary,
      tooltipSchemeColor: SchemeColor.onPrimaryContainer,
      dialogBackgroundSchemeColor: SchemeColor.onPrimary,
      dialogRadius: 20.0,
      timePickerDialogRadius: 20.0,
      bottomNavigationBarSelectedLabelSchemeColor: SchemeColor.secondary,
      bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.secondary,
      bottomNavigationBarSelectedIconSchemeColor: SchemeColor.secondary,
      bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.secondary,
      bottomNavigationBarBackgroundSchemeColor: SchemeColor.onPrimary,
      bottomNavigationBarShowUnselectedLabels: false,
      navigationRailSelectedLabelSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailUnselectedLabelSchemeColor: SchemeColor.primary,
      navigationRailSelectedIconSchemeColor: SchemeColor.onPrimaryContainer,
      navigationRailUnselectedIconSchemeColor: SchemeColor.primary,
      navigationRailIndicatorOpacity: 0.23,
      navigationRailLabelType: NavigationRailLabelType.selected,
    ),
    keyColors: const FlexKeyColors(
      useSecondary: true,
      useTertiary: true,
      keepTertiary: true,
      keepPrimaryContainer: true,
      keepTertiaryContainer: true,
    ),
    visualDensity: FlexColorScheme.comfortablePlatformDensity,
    useMaterial3: true,
    swapLegacyOnMaterial3: true,
  );
}
